ISO = "jeffnoxon/ubuntu-20.04-arm64"
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "ansible/inventory"

servers = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box_download_insecure = true
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "public_network"
      node.vm.provider "parallels" do |p|
        p.cpus = machine[:core]
        p.memory = machine[:ram]
        p.name = machine[:hostname]
      end
      node.vm.provision "shell", inline: <<-SHELL
        sudo apt update && apt upgrade -y 
        sudo apt install ansible -y
      SHELL
      node.vm.provision "ansible_local" do |setup|
        setup.inventory_path = INVENTORY_PATH
        setup.playbook = "ansible/provision.yml"
        setup.become = true 
      end
    end
  end
end

